######################################################################
# Automatically generated by qmake (3.0) mer. mai 17 12:55:42 2017
######################################################################

TEMPLATE = app
TARGET = appli
INCLUDEPATH += .

# Input
HEADERS += Chambre.hpp Database.hpp Telephone.hpp Traitement.hpp
SOURCES += Chambre.cpp Database.cpp main.cpp Telephone.cpp Traitement.cpp

QT += core websockets sql
QT -= gui
