######################################################################
# Automatically generated by qmake (3.0) mar. mai 16 09:43:54 2017
######################################################################

TEMPLATE = app
TARGET = appli
INCLUDEPATH += .

# Input
HEADERS += database.hpp websocket.hpp
SOURCES += database.cpp main.cpp websocket.cpp

QT += core websockets sql
QT -= gui
